upstream frontend {
    server codekids-frontend:3000;
}

upstream java_backend {
    server codekids-java:8080;
}

upstream python_backend {
    server codekids-python:5000;
}

upstream ai_service {
    server codekids-ai:8000;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend;
    }

    location /api/ {
        proxy_pass http://java_backend;
    }

    location /py/ {
        proxy_pass http://python_backend;
    }

    location /ai/ {
        proxy_pass http://ai_service;
    }
}
